apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: prod-ref-guide-ngm
  owner: prod-ref-guide-ngm
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/prod-ref-guide-ngm/multi-tenancy-gitops-apps.git
