apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCRG4qeI7mjjRn3ZL4bf1Km4HbVe71ociQiD/+vWCC9P1Qszvij+2iwqOJ8aTo8b0AD2wiwS9vNuoBtuQu5PXMEXYIMckJbitqOO3tGR6CaluVXwL2tXNRv1kVJEFspbfxWjtnVSZsMAbSz9NhnA9b6/tQw6ER82qaSbZaOtOEFjgRmUkVMmljttl6DxPUj7RQtRkdfu9v29UJn9GBXs9axTinYa7AiJEfmNabwtrKzbOBkpw+yARM711/V63IOFFcOM53CF+QQTibdmBYnOgdCKjDRo+qG+pj/muFA9fKZCG2DthutIYQiFDGtFfXq+jpG6KvNCsywkOGUGf2uMgV08Iut4ZRzdQ4EQDduNXKTJZgMSlmu9GU89oew8GlabSDuDVRy1gFZduEkqW36NBBHJPhjaFnZeZzdoa+jppuMCCB27TXpUT8eFfXsAzlUgme2cuRL+C2uzLUM6wV5X+nNIt2KaQ0CJESGH1nDgaEtPXF5MYUDL5++hDmHlqg4EcoG4wTphNIt8CgbugbAB0zSN5vOyKgN299AJjSR4NVB4mylc38BzpmKqpvouLU1Mf7Gaco+bAmw15mOrc3kRze8oTzB7eOxEXnuyBBqWRxXy8gex/HU/LsfO26NBF29hUzDhoQq/zDzofsITA+3fxPyeQVZru/f9KTcp2C8DKtDkuzACmuclKn3iB0JPs3whBQ0e7e469JO8bMzQmsMDLjDa5bViAZWvVFS60mdK2BJiUrOsYV30cJMpJrwsRdRpfvdvoJ+Ode1Y3/AEmwrbqkMM6qj/k+fiGtcSA685hpW3vv+P+tKNWhuldD+WpJHmGKlJALd82+fyThyonmVztm/+6Dpvn6wI6XouDnzoYa+6q51ZrelaTgehbaMKfkA1JsmdsBIS72xqYuCPM9FuL8/4XVxAilOTpBT+gRKEsiWnw==
    IBM_ENTITLED_REGISTRY_USER: AgBY/JmB0OnagailXQTc+PJH9f/lbLx/2b7fCFXLNWj52WtzAEpDz/BAWjLYI4A7Yra5Q7PaNG/eTG3oKNgaBNqKomyFl5T7pA73CWMxasTyVgjWmKHDV4Zvz/G11XCudkVlJflPMMtvpFFhdaxQcPw1Y2LDqkPEIk7d10cUlkga3FVKg8xGvkH82Qa23yyR//LAm3ukGn6yn7i8xz51+9x8C2ZgQcch8I7KGcMnUq2Juafmt4BaXaaUomWfnfZb7BKp62BhVVgVBT6blGBB/QYqGProtBqFcppeQqPCiIhQxvb3Whik7YO8gmfsG12tHQSEbjg49AhGZH8jME1tpcfGDvWunKuMkshngsrSghjQe2+p9f/d9nRo8xSoNyT+x9vpFckpwkJwo1IUUXf4wS/RkeApgiyIotGekKYc21Ep5lnF4fjIqddrKED/DuHiIIdqfwZ+RqjmKGqb+Vt6oqFTlcW5GaJM3FUbV1/BiRFsCnwddA8Fv7llnw7b0SBtMgrTEdtDNMYhBNyNlEBvw0JEK7DsgF3uM48yFEdi5kya3Ijkvk+vPn+HtUjT+DGwhn3/7EWD3A7U+CA5G05f73Bj4LmRK3a4ObVPWx538q6I6p484fnpa0jyPBKI17/nch1sG5yoiKFQInup0welav+sqDWrq+nOn/COzw15eGxYOO18ESt+sdrtLxaKAGR97E6i5A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

